### PR TITLE
Strict mode

### PR DESCRIPTION
**Pull request by sivaraam**
## Highlight
"Strict mode" enabled to avoid sloppy JS usage.

### CODE REVIEW

**Review by sirganeshv — COMMENTED** [review]
What is the need of let for currDate ?
The loop variable is the one that should be declared let instead of var

**Comment by sivaraam** [comment]
There's no hard and fast rule for declaring variables using `let`. I thought block-level scope was enough for `currDate` instead of the file level scope as a result of declaring it using `var`. Refer to SO link in first commit message. And yes, **read commit messages first**.

The variables (including loop variables) would be declared correctly in further refactorings. Of course, you could do that change if you wish :wink:

**Comment by sirganeshv** [comment]
Yes i know the purpose of commit messages
It seems you confused by reading a lot
Function level scope is enough for currDate which could be provided by both `var ` and `let` 
There is no much difference between them using here in this context.
And yes **var does not provide file level scope...It provides function level scope here**
Avoid using let
Note:
Browser compatibility should be taken into account
Not all have advanced browsers like developers

**Comment by sivaraam** [comment]
Maybe you're right. I got confused a little.

BTW Browser compatibility is required but considering Firefox as an **advanced** browser is a little too much.

**Comment by sirganeshv** [comment]
I did not mean Firefox as advanced
Rather the version we are using is advanced compared to what we have in our college(for whom we are supposed to be developing)
They may not be having 
*Firefox v44 and above or
*Chrome v41 and above or
*IE v11
Consider browser compatibility too
let was introduced 10 years after the JS was introduced
Kindly rethink

**Comment by sivaraam** [comment]
I guess it's time to start using [babel](https://babeljs.io/) ?

**Comment by sivaraam** [comment]
@sirganeshv So you have 2 options,
1.  merge this and we'll handle browser issues using babel
2.  reject this

Which one do you choose ?

**Comment by sivaraam** [comment]
And to add to the previous comment, if you chose the seecond option of rejecting this change and think of manually handling browser compatibility then I would like to inform you that the code base already uses other _more_ advanced JS constructs such as [destructive assignment](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) which are currently supported only in,
Chrome - 49+
Edge - 14
IE - Not supported

**Think and decide**

**Review by sirganeshv — APPROVED** [review]

**Pull request merged**
